version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"  # Expose le port 5000
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydatabase  # Remplacez par vos informations
    depends_on:
      - db

  db:
    image: postgres:13  # Utilise l'image officielle de PostgreSQL
    restart: always
    environment:
      POSTGRES_USER: user  # Remplacez par votre nom d'utilisateur
      POSTGRES_PASSWORD: password  # Remplacez par votre mot de passe
      POSTGRES_DB: mydatabase  # Remplacez par le nom de votre base de données
    volumes:
      - db_data:/var/lib/postgresql/data  # Persiste les données de la base de données

volumes:
  db_data:  # Définit un volume pour la base de données